---

- name: Update grub2
  shell: 'update-grub2'

- name: Find and absent old linux kernel
  shell: 'apt-get remove $(dpkg -l|egrep "^ii  linux-(im|he)"|awk "{print $2}"|grep -v `uname -r`)'

- name: Run dpkg reconfigure
  shell: 'dpkg --configure -a'
